# Generated by Django 5.2.11 on 2026-02-10 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_note_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nom de l'opportunité"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="Montant estimé (FCFA)",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("qualification", "Qualification"),
                            ("proposition", "Proposition envoyée"),
                            ("negociation", "Négociation"),
                            ("gagne", "Gagné (Fermé)"),
                            ("perdu", "Perdu (Fermé)"),
                        ],
                        default="qualification",
                        max_length=20,
                    ),
                ),
                (
                    "expected_close_date",
                    models.DateField(verbose_name="Date de clôture prévue"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-expected_close_date"],
            },
        ),
    ]
