# Generated by Django 5.2.11 on 2026-02-10 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_deal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Tâche à faire"),
                ),
                ("due_date", models.DateField(verbose_name="Date d'échéance")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("basse", "Basse"),
                            ("moyenne", "Moyenne"),
                            ("haute", "Haute"),
                        ],
                        default="moyenne",
                        max_length=10,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="leads.lead",
                    ),
                ),
            ],
        ),
    ]
