# Generated by Django 5.2.11 on 2026-02-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0007_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Adresse"),
        ),
        migrations.AlterField(
            model_name="client",
            name="date_converted",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de conversion"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="client",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="Prénom"),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="Téléphone"),
        ),
    ]
