# Generated by Django 5.2.11 on 2026-04-01 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nom de la catégorie"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_categories",
                        to="mplace.boutique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Désignation")),
                (
                    "sku",
                    models.CharField(max_length=50, verbose_name="Code Article / SKU"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.IntegerField(default=0, verbose_name="Stock Actuel"),
                ),
                (
                    "min_stock_level",
                    models.IntegerField(default=5, verbose_name="Seuil d'alerte"),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Prix d'achat"
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Prix de vente"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("unite", "Unité"),
                            ("kg", "Kilogramme"),
                            ("litre", "Litre"),
                            ("paquet", "Paquet"),
                        ],
                        default="unite",
                        max_length=20,
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_products",
                        to="mplace.boutique",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="mplace.categorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit",
                "verbose_name_plural": "Produits",
                "unique_together": {("boutique", "sku")},
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantité")),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("entree", "Entrée (Achat/Retour)"),
                            ("sortie", "Sortie (Vente/Perte)"),
                        ],
                        max_length=10,
                        verbose_name="Type de mouvement",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text="Ex:Vente client, Nouvel arrivage",
                        max_length=255,
                        verbose_name="Raison",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Date")),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="mplace.boutique",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vendeur / Auteur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom du fournisseur"),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nom du contact"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Téléphone")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="mplace.boutique",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="N° Commande"
                    ),
                ),
                (
                    "date_order",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de commande"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("commande", "Commandé"),
                            ("recu", "Reçu (Terminé)"),
                            ("annule", "Annulé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Montant total",
                    ),
                ),
                (
                    "date_received",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Date de réception effective",
                    ),
                ),
                (
                    "date_cancelled",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'annulation"
                    ),
                ),
                (
                    "expected_date",
                    models.DateField(
                        blank=True,
                        help_text="Date à laquelle le fournisseur a promis la livraison",
                        null=True,
                        verbose_name="Date de réception prévue",
                    ),
                ),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_orders",
                        to="mplace.boutique",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="inventory.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_ordered",
                    models.IntegerField(verbose_name="Quantité commandée"),
                ),
                (
                    "quantity_received",
                    models.IntegerField(default=0, verbose_name="Quantité reçue"),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="Prix d'achat unitaire",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                        verbose_name="Produit",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.supplierorder",
                        verbose_name="Commande",
                    ),
                ),
            ],
        ),
    ]
