# Generated by Django 5.2.11 on 2026-02-11 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nom de la catégorie"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Désignation")),
                (
                    "sku",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Code Article / SKU"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.IntegerField(default=0, verbose_name="Stock Actuel"),
                ),
                (
                    "min_stock_level",
                    models.IntegerField(default=5, verbose_name="Seuil d'alerte"),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Prix d'achat"
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Prix de vente"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("unite", "Unité"),
                            ("kg", "Kilogramme"),
                            ("litre", "Litre"),
                            ("paquet", "Paquet"),
                        ],
                        default="unite",
                        max_length=20,
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="inventory.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("entree", "Entrée (Achat/Retour)"),
                            ("sortie", "Sortie (Vente/Perte)"),
                        ],
                        max_length=10,
                        verbose_name="Type de mouvement",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text="Ex:Vente client, Nouvel arrivage",
                        max_length=255,
                        verbose_name="Raison",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Date")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.product",
                    ),
                ),
            ],
        ),
    ]
