# Generated by Django 5.2.11 on 2026-04-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default=1, upload_to="market/produits/"),
            preserve_default=False,
        ),
    ]
