# Generated by Django 5.2.11 on 2026-04-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False, verbose_name="Publier sur la Marketplace"
            ),
        ),
    ]
