# Generated by Django 5.2.11 on 2026-02-16 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_stockmovement_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom du fournisseur"),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nom du contact"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Téléphone")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adresse")),
            ],
        ),
        migrations.CreateModel(
            name="SupplierOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="N° Commande"
                    ),
                ),
                (
                    "date_order",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de commande"
                    ),
                ),
                (
                    "expected_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de réception prévue"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("commande", "Commandé"),
                            ("recu", "Reçu (Terminé)"),
                            ("annule", "Annulé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Montant total",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="inventory.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_ordered",
                    models.IntegerField(verbose_name="Quantité commandée"),
                ),
                (
                    "quantity_received",
                    models.IntegerField(default=0, verbose_name="Quantité reçue"),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="Prix d'achat unitaire",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                        verbose_name="Produit",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.supplierorder",
                        verbose_name="Commande",
                    ),
                ),
            ],
        ),
    ]
