# Generated by Django 5.2.11 on 2026-02-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_supplier_supplierorder_orderline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplierorder",
            name="expected_date",
        ),
        migrations.AddField(
            model_name="supplierorder",
            name="date_cancelled",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date d'annulation"
            ),
        ),
        migrations.AddField(
            model_name="supplierorder",
            name="date_received",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de réception effective"
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="quantity",
            field=models.IntegerField(verbose_name="Quantité"),
        ),
    ]
