# Generated by Django 5.2.11 on 2026-02-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_remove_supplierorder_expected_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierorder",
            name="expected_date",
            field=models.DateField(
                blank=True,
                help_text="Date à laquelle le fournisseur a promis la livraison",
                null=True,
                verbose_name="Date de réception prévue",
            ),
        ),
    ]
