# Generated by Django 5.2.11 on 2026-02-19 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "nom",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nom du formulaire",
                    ),
                ),
                (
                    "prenom",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Prénom du formulaire",
                    ),
                ),
                (
                    "has_file_upload",
                    models.BooleanField(
                        default=False, null=True, verbose_name="Contient des fichiers ?"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answers_data", models.JSONField(default=dict)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file_links",
                    models.TextField(
                        blank=True,
                        help_text="Liens vers les fichiers uploadés sur Google Drive",
                        null=True,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="kibo_forms.form",
                    ),
                ),
            ],
        ),
    ]
