# Generated by Django 5.2.11 on 2026-02-19 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kibo_forms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submission",
            options={
                "verbose_name": "Réponse reçue",
                "verbose_name_plural": "Réponses reçues",
            },
        ),
        migrations.AlterField(
            model_name="submission",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="kibo_forms.form",
                verbose_name="Formulaire associé",
            ),
        ),
    ]
