# Generated by Django 5.2.11 on 2026-02-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kibo_forms", "0002_alter_submission_options_alter_submission_form"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form",
            name="prenom",
        ),
        migrations.AlterField(
            model_name="form",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description du formulaire"
            ),
        ),
    ]
