# Generated by Django 5.2.11 on 2026-02-13 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="Montant du paiement",
                    ),
                ),
                (
                    "date_payment",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date du paiement"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Espèces"),
                            ("orange_money", "Orange Money"),
                            ("moov_money", "Moov Money"),
                            ("virement", "Virement"),
                        ],
                        default="cash",
                        max_length=50,
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="sales.sale",
                    ),
                ),
            ],
        ),
    ]
